version: '3.8'

# Production overrides for docker-compose.yml
services:
  barter-strategy:
    image: ghcr.io/taoseekai/barter-strategy:${VERSION:-latest}
    restart: always
    environment:
      - RUST_LOG=warn
      - RUST_BACKTRACE=0
      - TRADING_MODE=live
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  fluvio:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: barter-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - grafana
    networks:
      - barter-network

  # Backup service
  backup:
    image: postgres:15-alpine
    container_name: barter-backup
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-barter_secret}
    volumes:
      - ./backups:/backups
    command: |
      sh -c 'while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h postgres -U barter barter > /backups/barter_$$(date +%Y%m%d_%H%M%S).sql
        find /backups -name "*.sql" -mtime +7 -delete
        sleep 86400
      done'
    networks:
      - barter-network
    depends_on:
      - postgres
    profiles:
      - backup